services:
  notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app

  web:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - .:/usr/share/nginx/html:ro
